language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "mannyjimenez-github"
    token:
      secure: "ec6ddac86fa224456995dda1cec7afddc1817f78"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
